export enum TypeKeys {
  NODE_ONLINE = 'NODE_ONLINE',
  NODE_OFFLINE = 'NODE_OFFLINE',
  NODE_ADDED = 'NODE_ADDED',
  NODE_REMOVED = 'NODE_REMOVED',

  WORKER_PROCESSING = 'WORKER_PROCESSING',
  WORKER_SPAWNED = 'WORKER_SPAWNED',
  WORKER_KILLED = 'WORKER_KILLED',

  BALANCER_FLUSH = 'BALANCER_FLUSH',

  NODE_CALL_REQUESTED = 'NODE_CALL_REQUESTED',
  NODE_CALL_TIMEOUT = 'NODE_CALL_TIMEOUT',
  NODE_CALL_SUCCEEDED = 'NODE_CALL_SUCCEEDED',
  NODE_CALL_FAILED = 'NODE_CALL_FAILED'
}
